<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "localfix"
 *
 * Auto generated by Extension Builder 2015-04-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Localization Fix',
	'description' => 'Fixes issue #15339. for now only as extension.',
	'category' => 'plugin',
	'author' => 'Lars Peter Søndergaard',
	'author_email' => 'l.soendergaard@lichtflut-medien.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);